package dev.abelab.jphacks.db.mapper.base;

import dev.abelab.jphacks.db.entity.Participation;
import dev.abelab.jphacks.db.entity.ParticipationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ParticipationBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    long countByExample(ParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int deleteByExample(ParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("roomId") Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int insert(Participation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int insertSelective(Participation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    List<Participation> selectByExample(ParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    Participation selectByPrimaryKey(@Param("userId") Integer userId, @Param("roomId") Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Participation record, @Param("example") ParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Participation record, @Param("example") ParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Participation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Participation record);
}